version: '3.8'

services:
  web:
    image: my-rails-app
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0"
    volumes:
      - ".:/rails"
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=postgresql://db:5432/blog_development
      - SECRET_KEY_BASE=your_secret_key_base

  db:
    image: postgres:13
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=ahmedfadl
      - POSTGRES_PASSWORD='ahmedfadl'
      - POSTGRES_DB=blog_development

volumes:
  postgres_data:
